### ISSUE TITLE
Firing Range live site failing with 503

### ISSUE THREAD

**Issue by psiinon** [google/firing-range#32]
Example: https://public-firing-range.appspot.com/escape/serverside/escapeHtml/body?q=a
Our ZAP regression tests are failing ;)
https://github.com/zapbot/zap-mgmt-scripts/runs/6977470176?check_suite_focus=true

**Comment by psiinon** [comment]
Its still broken 😉

**Comment by mariussteffens** [comment]
Hey there, 

thanks for reaching out (and for keeping us on our toes :) )!

We just came out of a summit week, but we are looking into it!

Will keep you posted with details.

**Comment by mariussteffens** [comment]
So the issue with the public version of the firing range should be resolved. 

Let us know if you are still encountering any issues with it!

**Comment by psiinon** [comment]
Yeah - all good now :)
Many thanks!
