### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by andresriancho** [google/firing-range#8]
https://public-firing-range.appspot.com/reverseclickjacking/singlepage/ParameterInQuery/?q=foo and others in the same section yield `Invalid location of the vulnerable parameter.` and they should be showing something completely different.

**Comment by mikispag** [comment]
Thanks for reporting this.

I have isolated the problem and will fix this today.

**Comment by andresriancho** [comment]
Thanks :+1:

**Comment by paradoxengine** [comment]
The links should now be fixed in the live version too. Sorry it took forever to push.

**Comment by andresriancho** [comment]
:+1:
